# Generated by Django 5.0.6 on 2024-07-11 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=300)),
                (
                    "image_mobile",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "image_large",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("type", models.CharField(max_length=15)),
                ("proteins", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("carbohydrates", models.IntegerField()),
                ("calories", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("password", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
        ),
    ]
