# Generated by Django 5.0.6 on 2024-07-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("burger_back", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="_id",
        ),
    ]
